# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iris_features_pb/iris_features.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'iris_features_pb/iris_features.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$iris_features_pb/iris_features.proto\x12\x10iris_features_pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n\x0cIrisFeatures\x12/\n\x0breceived_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0csepal_length\x18\x02 \x01(\x02\x12\x13\n\x0bsepal_width\x18\x03 \x01(\x02\x12\x14\n\x0cpetal_length\x18\x04 \x01(\x02\x12\x13\n\x0bpetal_width\x18\x05 \x01(\x02\"N\n\x10IrisFeaturesList\x12:\n\x12iris_features_list\x18\x01 \x03(\x0b\x32\x1e.iris_features_pb.IrisFeatures\"\x83\x01\n\x18IrisFeaturesPreProcessed\x12\x30\n\x0cprocessed_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\riris_features\x18\x02 \x01(\x0b\x32\x1e.iris_features_pb.IrisFeatures\"k\n\x1cIrisFeaturesPreProcessedList\x12K\n\x17iris_features_processed\x18\x01 \x03(\x0b\x32*.iris_features_pb.IrisFeaturesPreProcessed\"\xb5\x01\n\x16IrisFeaturesClassified\x12\x31\n\rclassified_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1b\n\x13iris_classification\x18\x02 \x01(\t\x12K\n\x17iris_features_processed\x18\x03 \x01(\x0b\x32*.iris_features_pb.IrisFeaturesPreProcessed\"h\n\x1aIrisFeaturesClassifiedList\x12J\n\x18iris_features_classified\x18\x01 \x03(\x0b\x32(.iris_features_pb.IrisFeaturesClassified\"\xba\x01\n\x19IrisFeaturesPostProcessed\x12\x35\n\x11post_processed_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1a\n\x12post_process_label\x18\x02 \x01(\t\x12J\n\x18iris_features_classified\x18\x03 \x01(\x0b\x32(.iris_features_pb.IrisFeaturesClassified\"r\n\x1dIrisFeaturesPostProcessedList\x12Q\n\x1ciris_features_post_processed\x18\x01 \x03(\x0b\x32+.iris_features_pb.IrisFeaturesPostProcessedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iris_features_pb.iris_features_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IRISFEATURES']._serialized_start=92
  _globals['_IRISFEATURES']._serialized_end=241
  _globals['_IRISFEATURESLIST']._serialized_start=243
  _globals['_IRISFEATURESLIST']._serialized_end=321
  _globals['_IRISFEATURESPREPROCESSED']._serialized_start=324
  _globals['_IRISFEATURESPREPROCESSED']._serialized_end=455
  _globals['_IRISFEATURESPREPROCESSEDLIST']._serialized_start=457
  _globals['_IRISFEATURESPREPROCESSEDLIST']._serialized_end=564
  _globals['_IRISFEATURESCLASSIFIED']._serialized_start=567
  _globals['_IRISFEATURESCLASSIFIED']._serialized_end=748
  _globals['_IRISFEATURESCLASSIFIEDLIST']._serialized_start=750
  _globals['_IRISFEATURESCLASSIFIEDLIST']._serialized_end=854
  _globals['_IRISFEATURESPOSTPROCESSED']._serialized_start=857
  _globals['_IRISFEATURESPOSTPROCESSED']._serialized_end=1043
  _globals['_IRISFEATURESPOSTPROCESSEDLIST']._serialized_start=1045
  _globals['_IRISFEATURESPOSTPROCESSEDLIST']._serialized_end=1159
# @@protoc_insertion_point(module_scope)
